# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db6855e4034d151a9a8ea3abb0c912e175a76db0a567112a282015c6ef2731798a49166a0f9985100792d3f7dbb7c12eb166b06ebfb1445b426d866863f52374

test:
  secret_key_base: 14067ca8cc0665b8c457dca69aaceb480f45fbdf48a68e1e46890ef1d9409810aa065ee5084db25423271a77140677f607830ccd8343770955d998364afd5d9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
